// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppcaxunnvacsoaezifnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwY2F4dW5udmFjc29hZXppZm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQzODMsImV4cCI6MjA1OTY4MDM4M30.XkWIMlAVHwAfOcMlcQJYAFLHl3xi1A9ELxySwL5o-F8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);